# @package _global_

# python -m main shortcode=exp/minecraft/eqf/infer_noiselevel +name=infer_noiselevel_eqf_minecraft wandb.mode=dryrun

# Inference time schedule sd3 for blind fm model


defaults:
  # model config such as size and inference params
  - model_config/cogv/100m

  # Shared across models for a particular dataset
  - exp/minecraft/minecraft_base

  - _self_
  - override /algorithm: noiselevelpred_eqf_video


dataset:
  max_frames: 300
  n_frames: 300
  num_validation_clips: 32

experiment:
  tasks: ['validation']
  devices: "auto"

  validation:
    precision: 16
    batch_size: 8
    dataloader:
      shuffle: false
    sample_during_training: true


algorithm:
  logging:
    inference_step_to_noise_level_thresholds: [0.5, 0.3, 0.1, 0.05, 0.01] # ; requires readout-enabled model
  tasks:
    prediction:
      streaming:
        sliding_context_frames: 25
        initial_context_frames: 25
        stride_in_frames: 1
        emit_eps: 0.0 # adaptive: block residual threshold
        frame_done_eps: 0.0 # adaptive: per-frame freeze threshold
        stop_based_on: gradnorm # gradnorm or readout
        emit_noise_level: 0.0 # adaptive readout: block noise level threshold
        frame_done_noise_level: 0.0 # adaptive readout: per-frame freeze threshold
        max_cycles_without_emit: default # max number of inner loops allowed between emitting a prefix
  denoising:
    equilibrium_lambda: 1.0
    equilibrium_schedule: constant
    sampling_algorithm: gd # gd, ngd
    num_sampling_steps: 250
    default_eta_multiple: 1.0
    mu: 0.0
    inference_schedule:
      enabled: true
      family: sd3 # identity, sd3, linear_logsnr, c_function
      t_end: 0.001
      sd3:
        r: 3.0
      c_function:
        schedule: truncated # linear, truncated, constant
        truncated_a: 0.8
      inference_solver_index_source: readout_predicted # schedule, readout_predicted

load: ${algorithm.model_weights.minecraft.noiselevelpred.eqf}
